import re, os, subprocess, urllib.request

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")
OUT = 'public/fonts'
os.makedirs(OUT, exist_ok=True)
css_parts = []

# url -> local filename. Variable fonts serve every weight from ONE file, so the
# filename must be keyed by URL, not by the weight of the block referencing it.
by_url = {}

def fetch(spec, name):
    url = f"https://fonts.googleapis.com/css2?family={spec}&display=swap"
    raw = subprocess.run(['curl', '-sS', '-A', UA, url], capture_output=True, text=True).stdout
    blocks = re.findall(r'/\*\s*([a-z\-\[\]0-9 ]+)\s*\*/\s*(@font-face\s*\{[^}]*\})', raw)
    if not blocks:
        blocks = [('latin', m) for m in re.findall(r'(@font-face\s*\{[^}]*\})', raw)]

    kept = 0
    for subset, block in blocks:
        subset = subset.strip()
        if subset not in ('latin', 'latin-ext'):
            continue
        m = re.search(r'url\((https://[^)]+\.woff2)\)', block)
        if not m:
            continue
        src = m.group(1)

        if src not in by_url:
            wm = re.search(r'font-weight:\s*([^;]+);', block)
            weight = (wm.group(1) if wm else '400').strip().replace(' ', '-')
            fname = f"{name}-{subset}-{weight}.woff2"
            req = urllib.request.Request(src, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req) as r, open(os.path.join(OUT, fname), 'wb') as f:
                f.write(r.read())
            by_url[src] = fname

        block = block.replace(src, f"/fonts/{by_url[src]}")
        block = re.sub(r'\}\s*$', '  font-display: swap;\n}', block)
        css_parts.append(block)
        kept += 1
    print(f"  {name}: {kept} face(s)")

fetch("Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700", "fraunces")
fetch("Inter:wght@400;500;600;700", "inter")
fetch("Caveat:wght@400;500;600;700", "caveat")
fetch("Patrick+Hand", "patrickhand")
fetch("Homemade+Apple", "homemadeapple")
fetch("Kalam:wght@300;400;700", "kalam")
fetch("Gloria+Hallelujah", "gloria")

header = ("/* Self-hosted subsets of the Google Fonts used by Pagebound.\n"
          "   Generated by scripts/fetch-fonts.py - see README. All are licensed\n"
          "   under the SIL Open Font License 1.1. */\n\n")
open(os.path.join(OUT, 'fonts.css'), 'w').write(header + '\n'.join(css_parts) + '\n')
print(f"files: {len(by_url)}  css blocks: {len(css_parts)}")
